name: Build Onion
on:
  push:
  workflow_dispatch:

env:
  REPOSITORY: "OnionUI/Onion"
  BRANCH: "main"

jobs:
  build:
    name: Build Onion
    runs-on: ubuntu-latest
    container:
      image: aemiii91/miyoomini-toolchain:latest
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY }}
        ref: ${{ env.BRANCH }}
        fetch-depth: 0
        submodules: recursive

    - name: Configure git
      run: git config --global --add safe.directory /__w/Onion/Onion

    - name: Setup build variable
      run: echo "BUILD_VERSION=$(make version)" >> $GITHUB_ENV

    - name: Configure Drastic defaults
      env:
        DS_PATH: static/packages/Emu/Nintendo - DS (Drastic)/Emu/NDS
      run: |
        echo "1600" > static/configs/RetroArch/cpuclock.txt
        sed -i 's/cpuclock 1500/cpuclock 1600/' "$DS_PATH/launch.sh"
        sed -i 's/"theme":./"theme":7/'   "$DS_PATH/resources/settings.json"
        sed -i 's/"mode":./"mode":1/'     "$DS_PATH/resources/settings.json"
        sed -i 's/"alpha":./"alpha":5/'   "$DS_PATH/resources/settings.json"
        sed -i 's/"border":./"border":5/' "$DS_PATH/resources/settings.json"

    - name: Configure Retroarch defaults
      env:
        RA_PATH: static/configs/RetroArch/.retroarch
      run: |
        sed -i 's/content_runtime_log.*/content_runtime_log = "false"/'            $RA_PATH/retroarch.cfg
        sed -i 's/quick_menu_show_cheats.*/quick_menu_show_cheats = "true"/'       $RA_PATH/retroarch.cfg
        sed -i 's/apply_cheats_after_load.*/apply_cheats_after_load = "true"/'     $RA_PATH/retroarch.cfg
        sed -i 's/apply_cheats_after_toggle.*/apply_cheats_after_toggle = "true"/' $RA_PATH/retroarch.cfg

    - name: Configure gpSP defaults
      env:
        SA_PATH: static/configs/Saves/CurrentProfile/config
      run: |
        sed -i 's/gpsp_color_correction.*/gpsp_color_correction = "enabled"/' $SA_PATH/gpSP/gpSP.opt
        sed -i 's/gpsp_frame_mixing.*/gpsp_frame_mixing = "enabled"/'         $SA_PATH/gpSP/gpSP.opt
        sed -i '$a\input_overlay_opacity = "0.500000"'                        $SA_PATH/gpSP/gpSP.cfg
        sed -i '$a\input_overlay = ":/.retroarch/overlay/GBA/GBA_REAL_3x-clean.cfg"' $SA_PATH/gpSP/gpSP.cfg
        sed -i '$a\video_filter = ":/.retroarch/filters/video/Normal/Normal2x.filt"' $SA_PATH/gpSP/gpSP.cfg
        sort -o $SA_PATH/gpSP/gpSP.cfg $SA_PATH/gpSP/gpSP.cfg

    - name: Configure Supafaust defaults
      env:
        SA_PATH: static/configs/Saves/CurrentProfile/config
      run: |
        sed -i '$a\input_overlay_opacity = "0.700000"'                               $SA_PATH/Supafaust/Supafaust.cfg
        sed -i '$a\video_dingux_ipu_filter_type = "1"'                               $SA_PATH/Supafaust/Supafaust.cfg
        sed -i '$a\video_filter = ":/.retroarch/filters/video/Normal/Normal2x.filt"' $SA_PATH/Supafaust/Supafaust.cfg
        sed -i '$a\input_overlay = ":/.retroarch/overlay/4-3/CRT/Perfect_CRT(read-instructions)/Perfect_CRT-noframe.cfg"' $SA_PATH/Supafaust/Supafaust.cfg
        sort -o $SA_PATH/Supafaust/Supafaust.cfg $SA_PATH/Supafaust/Supafaust.cfg
        #echo 'video_scale_integer = "true"' >> $SA_PATH/Supafaust/Supafaust.cfg
        #echo 'video_dingux_ipu_keep_aspect = "true"' >> $SA_PATH/Supafaust/Supafaust.cfg

    - name: Configure PCSX-ReARMed defaults
      env:
        SA_PATH: static/configs/Saves/CurrentProfile/config
      run: |
        sed -i 's/pcsx_rearmed_dithering.*/pcsx_rearmed_dithering = "enabled"/' $SA_PATH/PCSX-ReARMed/PCSX-ReARMed.opt
        sed -i '$a\input_overlay_opacity = "0.700000"'                          $SA_PATH/PCSX-ReARMed/PCSX-ReARMed.cfg
        sed -i '$a\input_overlay = ":/.retroarch/overlay/4-3/CRT/Perfect_CRT(read-instructions)/Perfect_CRT-noframe.cfg"' $SA_PATH/PCSX-ReARMed/PCSX-ReARMed.cfg
        sort -o $SA_PATH/PCSX-ReARMed/PCSX-ReARMed.cfg $SA_PATH/PCSX-ReARMed/PCSX-ReARMed.cfg

    - name: Build Onion-v${{ env.BUILD_VERSION }}
      shell: bash
      run: |
        source /root/.bashrc
        VERSION_OVERRIDE=${{ env.BUILD_VERSION }} make release

    - name: Upload release
      uses: actions/upload-artifact@main
      with:
        retention-days: 1
        name: Onion-v${{ env.BUILD_VERSION }}
        path: release/Onion-v${{ env.BUILD_VERSION }}.zip

  release:
    needs: build
    uses: filterpaper/scripts/.github/workflows/publish-artifact.yml@main
    with:
      release_name: OnionOS
      release_tag: latest

  purge:
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main
    with:
      purge-age: 3
      delete-all-completed: false
      delete-all-incomplete: false
